CREATE ROLE backend_dev WITH LOGIN PASSWORD 'backend_dev_123';
CREATE ROLE bi_dev WITH LOGIN PASSWORD 'bi_dev_123';
CREATE ROLE data_engineer WITH LOGIN PASSWORD 'data_engineer_123';

-- backend_dev: CRUD
GRANT USAGE ON SCHEMA SALAM TO backend_dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALAM TO backend_dev;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA SALAM TO backend_dev;
GRANT UPDATE ON ALL SEQUENCES IN SCHEMA SALAM TO backend_dev;

-- bi_dev: hanya SELECT
GRANT USAGE ON SCHEMA SALAM TO bi_dev;
GRANT SELECT ON ALL TABLES IN SCHEMA SALAM TO bi_dev;

-- data_engineer: CREATE, MODIFY, DROP + CRUD
GRANT USAGE ON SCHEMA SALAM TO data_engineer;
GRANT ALL PRIVILEGES ON SCHEMA SALAM TO data_engineer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SALAM TO data_engineer;
